name: customer
description: Coustomer Application

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+3

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  google_fonts: ^4.0.3
  iconify_flutter: ^0.0.5
  dropdown_button2: ^2.0.0
  circle_flags: ^1.0.3
  pinput: ^2.2.16
  flag: ^6.0.0
  flutter_svg: ^1.1.6
  http: ^0.13.5
  google_maps_flutter: ^2.2.1
  geolocator: ^9.0.2
  geocoding: ^2.0.5
  sliding_up_panel: any
  provider: ^6.0.4
  sn_progress_dialog: ^1.0.9
  flutter_polyline_points: ^1.0.0
  dotted_border: ^2.0.0+3
  # slide_to_act: ^2.0.1
  carousel_slider: ^4.2.1
  socket_io_client: ^2.0.1
  camera: ^0.11.0+1
  firebase_core: ^2.4.1
  firebase_storage: ^11.0.10
  firebase_dynamic_links: ^5.0.11
  loading_animation_widget: ^1.2.0+4
  video_player: ^2.5.1
  shared_preferences: ^2.0.17
  share_plus: ^6.3.1
  url_launcher: ^6.1.9
  firebase_auth: ^4.2.9
  flutter_html: ^3.0.0-alpha.6
  google_sign_in: ^6.0.1
  flutter_facebook_auth: ^5.0.7
  sign_in_with_apple: ^4.3.0
  # otp_autofill: ^2.1.0
  # alt_sms_autofill: ^1.0.0
  glassmorphism: ^3.0.0
  # flutter_neumorphic: ^3.2.0
  flutter_phoenix: ^1.1.1
  animated_text_kit: ^4.2.2
  slide_to_act: ^2.0.2
  change_app_package_name: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - images/
