// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYXUanzBpIaJMv8UGmwdFYEdt1Va9UhMY',
    appId: '1:445786694458:web:2e2a6c0875b64781d0e603',
    messagingSenderId: '445786694458',
    projectId: 'switch-ev',
    authDomain: 'switch-ev.firebaseapp.com',
    storageBucket: 'switch-ev.appspot.com',
    measurementId: 'G-ESY6K98RZ4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPOcPWQs7F2Fxc2lmKnXtplNeT_zLORW4',
    appId: '1:445786694458:android:69a10b428bd5132ed0e603',
    messagingSenderId: '445786694458',
    projectId: 'switch-ev',
    storageBucket: 'switch-ev.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBpu9iza_3DXH5gdTa-p7Y43qMmZ8BqYzE',
    appId: '1:445786694458:ios:2e5c764e60d5a7e4d0e603',
    messagingSenderId: '445786694458',
    projectId: 'switch-ev',
    storageBucket: 'switch-ev.appspot.com',
    iosClientId: '445786694458-lc3e3lekdkqehenv009mecv14uc8saem.apps.googleusercontent.com',
    iosBundleId: 'com.example.customer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBpu9iza_3DXH5gdTa-p7Y43qMmZ8BqYzE',
    appId: '1:445786694458:ios:2e5c764e60d5a7e4d0e603',
    messagingSenderId: '445786694458',
    projectId: 'switch-ev',
    storageBucket: 'switch-ev.appspot.com',
    iosClientId: '445786694458-lc3e3lekdkqehenv009mecv14uc8saem.apps.googleusercontent.com',
    iosBundleId: 'com.example.customer',
  );
}
